### ISSUE TITLE
Integrated testing

### ISSUE THREAD

**Issue by n-wach** [FLIR/conservator-cli#132]
In order of priority:

- [ ] Local dataset functions (correspond to cvc commands)
- [ ] Test basic object creation/deletion/modification
- [ ] Construct/destruct test objects instead of using hardcoded (use fixtures, may require uploading files)
- [ ] Test that all command line commands don't error (see if click has support for this)
- [ ] Reimplement most examples as tests
- [ ] Go through API reference and add additional tests

**Comment by shiftycow** [comment]
https://jiracommercial.flir.com/browse/CON-1250

**Comment by n-wach** [comment]
We will track this internally via JIRA
