### ISSUE TITLE
Change default config path, named configs

### ISSUE THREAD

**Issue by n-wach** [FLIR/conservator-cli#164]
It might be better form to store the config in `~/.config/conservator/default.json` instead of `~/.conservator_config.json`

I'm not sure how useful this would be outside of CLI developers (as most only use one conservator instance), but we can add support for "naming" configs, and save/load them:

`conservator config create "staging"`
`conservator config create "prod"`
`conservator config set-default "staging"`

Although I don't know the implications for this re: other config sources or migrating existing configs

**Comment by shiftycow** [comment]
I would suggest mimicking how AWS CLI works. There are a couple files:
~/.aws/config
~/.aws/credentials

In the `config` file are named profiles with URLs and other parameters. The `credentials` file stores the credentials for each profile. You can switch between them with an environment variable (e.g. `export AWS_PROFILE=flir` ) or with a flag on the command line.

https://jiracommercial.flir.com/browse/CON-1248
