### ISSUE TITLE
Add method for getting Image/Video frame by index/id

### ISSUE THREAD

**Issue by n-wach** [FLIR/conservator-cli#186]
Frequent pattern in ConservatorTools scripts

Suggested methods:
`Image.get_frame_by_index(index, fields)`
`Image.get_frame(fields)` (images only have one frame)
`Image.get_frame_by_id(id, fields)`

`Video.get_frame_by_index(index, fields)`
`Video.get_frame_by_id(id, fields)`

**Comment by shiftycow** [comment]
https://jiracommercial.flir.com/browse/CON-1247
