### ISSUE TITLE
Remove problematic fields

### ISSUE THREAD

**Issue by n-wach** [FLIR/conservator-cli#194]
We don't request all fields anymore, and the errors we're currently handling shouldn't appear in normal use. 

The handling complicates a lot of the request logic, and could potentially have very unexpected side effects (calling mutations multiple times, etc.). I think it's best if we remove all of this logic. If someone encounters a field that causes an error, it should really be reported and fixed in Conservator backend--not ignored

**Comment by shiftycow** [comment]
https://jiracommercial.flir.com/browse/CON-1246
