### ISSUE TITLE
Add CLI option for specifying config

### ISSUE THREAD

**Issue by n-wach** [FLIR/conservator-cli#199]
Extending #164 

We want configs to be easily specified for individual CLI commands. This involves creating a `Conservator` context object in the `conservator` command based on options, and passing it to all subcommands to use.

We will add a `--config` option to specify config name, potentially also let API key, url, etc. be specified to create a one-off config for the command. 

Config won't always exist--such as during intial setup. Also, `Conservator` context may conflict with the `LocalDataset` context CVC subcommands pass around.

**Comment by SJLC** [comment]
The cvc context can be a dict rather than a string, for extensibility

[DIFF.txt](https://github.com/FLIR/conservator-cli/files/6025282/DIFF.txt)

**Comment by shiftycow** [comment]
https://jiracommercial.flir.com/browse/CON-1245

**Comment by n-wach** [comment]
We will track this internally via JIRA
