### ISSUE TITLE
Installation fails on fresh Ubuntu 20.04 system

### ISSUE THREAD

**Issue by filitchp** [FLIR/conservator-cli#281]
On a fresh Ubuntu 20.04 system the path `~/.local/bin` does not exist and as a result it is not in the `$PATH`
Here's what `PATH` looks like on a fresh install:
```
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

`pip` will create `~/.local/bin` on a fresh install, _but_ it's still not in the path. So installing Conservator CLI fails out of box because the `conservator` cannot be found.

```bash
Successfully installed Pillow-9.0.1 attrs-21.4.0 click-8.0.3 conservator-cli-2.0.0 graphql-core-3.2.0 importlib-resources-5.4.0 jsonschema-4.4.0 pyrsistent-0.18.1 sgqlc-15.0 tqdm-4.62.3 zipp-3.7.0
ubuntu@budgie20:~$ conservator
conservator: command not found
```

See the following thread:
https://askubuntu.com/questions/1144231/home-local-bin-not-in-path-for-ubuntu-19-04

The suggestion from the thread is to run `source ~/.profile` after doing the install on a fresh system.

This fix works from personal testing. 

```bash
ubuntu@budgie20:~$ conservator
conservator: command not found
ubuntu@budgie20:~$ source ~/.profile
ubuntu@budgie20:~$ conservator
Usage: conservator [OPTIONS] COMMAND [ARGS]...
...
```

**Comment by SJLC** [comment]
Thanks, it is now in docs
